
'use client'

import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from '@/components/ui/card'
import { Textarea } from '@/components/ui/textarea'
import { Loader2, Sparkles, Mic } from 'lucide-react'

export function AIClient() {
    const [query, setQuery] = useState('')
    const [insight, setInsight] = useState('')
    const [loading, setLoading] = useState(false)

    const handleAnalyze = async () => {
        setLoading(true)
        try {
            const res = await fetch('/api/ai/analyze', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({ query })
            })

            if (!res.ok) {
                throw new Error('Failed to fetch insights')
            }

            const data = await res.json()
            setInsight(data.insight)
        } catch (error) {
            console.error(error)
            setInsight('Sorry, I could not generate an insight at this time.')
        } finally {
            setLoading(false)
        }
    }

    return (
        <div className="grid gap-6">
            <Card>
                <CardHeader>
                    <CardTitle>Ask PayAware AI</CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                    <Textarea
                        placeholder="e.g., What is my highest expense category this month?"
                        value={query}
                        onChange={(e) => setQuery(e.target.value)}
                    />
                    <div className="text-xs text-muted-foreground">
                        AI will analyze your recent transactions to answer.
                    </div>
                </CardContent>
                <CardFooter>
                    <Button onClick={handleAnalyze} disabled={loading} className="w-full sm:w-auto">
                        {loading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Sparkles className="mr-2 h-4 w-4" />}
                        Generate Insight
                    </Button>
                </CardFooter>
            </Card>

            {insight && (
                <Card className="bg-slate-50 dark:bg-slate-900 border-blue-100 dark:border-blue-900">
                    <CardHeader>
                        <CardTitle className="text-blue-700 dark:text-blue-300">Analysis Result</CardTitle>
                    </CardHeader>
                    <CardContent>
                        <div className="prose dark:prose-invert">
                            {insight}
                            {/* Render markdown if we wanted, but text is fine for now */}
                        </div>
                    </CardContent>
                    <CardFooter>
                        <p className="text-xs text-muted-foreground italic">
                            Disclaimer: This is generated by AI and is for informational purposes only. Not financial advice.
                        </p>
                    </CardFooter>
                </Card>
            )}
        </div>
    )
}
